name: libd
description: Lua interpreter by dart
version: 1.0.0
homepage: https://github.com/arcticfox1919/libd

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  sprintf: "^5.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
